name: keylol action
on:
  schedule:
    - cron: "0 10 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Keylol Action
        uses: yuyinws/keylol-action@v1.1
        with:
          urls: 
            f319-1
            f234-1
          limit: 5

      - name: Send mail
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          # smtp 服务器地址
          server_address: smtp.qq.com
          # smtp 服务器端口
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Keylol帖子订阅邮件
          html_body: file://context.html
          to: ${{ secrets.TARGET_MAIL }}
          from: yuyin
          convert_markdown: true
